"""
Argon2-CFFI Password Hashing Manager

Implements secure password hashing using Argon2-CFFI (PHC winner)
This is more secure than bcrypt or SHA-256 for password storage.

Reference: https://github.com/hynek/argon2-cffi
"""

import os
import argon2
import secrets
import logging
from typing import Tuple, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class Argon2Manager:
    """
    Manager for Argon2-CFFI password hashing

    Uses Argon2id (recommended for password hashing) which combines
    resistance to side-channel attacks (Argon2i) and GPU/ASIC attacks (Argon2d)
    """

    # Recommended parameters (2024 OWASP guidelines)
    # These can be adjusted based on security requirements and performance constraints
    TIME_COST = 3  # Number of iterations (higher = more secure but slower)
    MEMORY_COST = 65536  # Memory cost in KiB (64MB) - prevents GPU/ASIC attacks
    PARALLELISM = 4  # Number of parallel threads
    HASH_LEN = 32  # Hash length in bytes (256 bits)
    SALT_LEN = 16  # Salt length in bytes (128 bits)

    def __init__(self,
                 time_cost: int = None,
                 memory_cost: int = None,
                 parallelism: int = None,
                 hash_len: int = None,
                 salt_len: int = None):
        """
        Initialize Argon2 password hasher

        Args:
            time_cost: Number of iterations (default: 3)
            memory_cost: Memory cost in KiB (default: 65536 = 64MB)
            parallelism: Number of parallel threads (default: 4)
            hash_len: Hash length in bytes (default: 32)
            salt_len: Salt length in bytes (default: 16)
        """
        self.time_cost = time_cost or self.TIME_COST
        self.memory_cost = memory_cost or self.MEMORY_COST
        self.parallelism = parallelism or self.PARALLELISM
        self.hash_len = hash_len or self.HASH_LEN
        self.salt_len = salt_len or self.SALT_LEN

        # Initialize Argon2 hasher
        self.hasher = argon2.PasswordHasher(
            time_cost=self.time_cost,
            memory_cost=self.memory_cost,
            parallelism=self.parallelism,
            hash_len=self.hash_len,
            salt_len=self.salt_len,
            type=argon2.Type.ID  # Argon2id (recommended for passwords)
        )

        logger.info(f"Argon2 Manager initialized (time_cost={self.time_cost}, "
                   f"memory_cost={self.memory_cost} KiB, parallelism={self.parallelism})")

    def hash_password(self, password: str) -> str:
        """
        Hash a password using Argon2-CFFI

        The hash includes all parameters and the salt in the output string,
        so it can be verified without storing salt separately.

        Args:
            password: Plain text password to hash

        Returns:
            Hashed password string (format: $argon2id$v=19$m=65536,t=3,p=4$...)

        Raises:
            ValueError: If password is empty or too short
        """
        if not password:
            raise ValueError("Password cannot be empty")

        if len(password) < 8:
            logger.warning("Password is shorter than recommended 8 characters")

        try:
            # Hash password with random salt (automatically generated by Argon2)
            hashed_password = self.hasher.hash(password)

            logger.debug(f"Password hashed successfully (length: {len(hashed_password)})")
            return hashed_password

        except Exception as e:
            logger.error(f"Failed to hash password: {e}")
            raise

    def verify_password(self, stored_hash: str, provided_password: str) -> bool:
        """
        Verify a password against a stored hash

        Args:
            stored_hash: Previously hashed password (from hash_password())
            provided_password: Plain text password to verify

        Returns:
            True if password matches, False otherwise
        """
        if not stored_hash:
            raise ValueError("Stored hash cannot be empty")

        if not provided_password:
            return False

        try:
            # Verify password (raises VerifyMismatchError if incorrect)
            self.hasher.verify(stored_hash, provided_password)
            logger.debug("Password verified successfully")
            return True

        except argon2.exceptions.VerifyMismatchError:
            logger.warning("Password verification failed (incorrect password)")
            return False

        except Exception as e:
            logger.error(f"Failed to verify password: {e}")
            return False

    def needs_rehash(self, stored_hash: str) -> bool:
        """
        Check if a stored password needs to be rehashed

        This is useful when security parameters are updated (e.g., increasing
        memory_cost or time_cost). Old hashes should be rehashed with new
        parameters on next successful login.

        Args:
            stored_hash: Previously hashed password

        Returns:
            True if password should be rehashed, False otherwise
        """
        try:
            needs_update = self.hasher.check_needs_rehash(stored_hash)
            if needs_update:
                logger.info("Password needs to be rehashed with new parameters")
            return needs_update
        except Exception as e:
            logger.error(f"Failed to check rehash: {e}")
            return False

    def generate_salt(self) -> bytes:
        """
        Generate a cryptographically secure random salt

        Note: Argon2 automatically generates a random salt when hashing,
        but this method is provided if a custom salt is needed.

        Args:
            None

        Returns:
            Random salt bytes
        """
        salt = secrets.token_bytes(self.salt_len)
        logger.debug(f"Generated random salt (length: {len(salt)})")
        return salt

    def get_hash_info(self, hashed_password: str) -> dict:
        """
        Extract information from an Argon2 hash

        Args:
            hashed_password: Hashed password string

        Returns:
            Dictionary with hash parameters (algorithm, version, time_cost, memory_cost, parallelism)
        """
        try:
            # Parse hash format: $argon2id$v=19$m=65536,t=3,p=4$salt$hash
            parts = hashed_password.split('$')

            if len(parts) < 6:
                raise ValueError("Invalid Argon2 hash format")

            info = {
                'algorithm': parts[1],
                'version': parts[2].replace('v=', ''),
                'params': parts[3]  # m=65536,t=3,p=4
            }

            # Parse parameters
            params = info['params'].split(',')
            for param in params:
                key, value = param.split('=')
                if key == 'm':
                    info['memory_cost'] = int(value)
                elif key == 't':
                    info['time_cost'] = int(value)
                elif key == 'p':
                    info['parallelism'] = int(value)

            return info

        except Exception as e:
            logger.error(f"Failed to parse hash info: {e}")
            return {}


# Singleton instance for convenient access
_default_argon2_manager = None


def get_argon2_manager() -> Argon2Manager:
    """
    Get the default Argon2 manager instance

    Returns:
        Argon2Manager instance
    """
    global _default_argon2_manager
    if _default_argon2_manager is None:
        _default_argon2_manager = Argon2Manager()
    return _default_argon2_manager


def hash_password(password: str) -> str:
    """
    Convenience function to hash a password using default Argon2 manager

    Args:
        password: Plain text password to hash

    Returns:
        Hashed password string
    """
    manager = get_argon2_manager()
    return manager.hash_password(password)


def verify_password(stored_hash: str, provided_password: str) -> bool:
    """
    Convenience function to verify a password using default Argon2 manager

    Args:
        stored_hash: Previously hashed password
        provided_password: Plain text password to verify

    Returns:
        True if password matches, False otherwise
    """
    manager = get_argon2_manager()
    return manager.verify_password(stored_hash, provided_password)


# Example usage
if __name__ == "__main__":
    print("=" * 60)
    print("Argon2-CFFI Password Hashing Example")
    print("=" * 60)

    # Initialize manager
    manager = Argon2Manager()

    # Test password hashing
    test_password = "MySecurePassword123!"

    print(f"\nTesting password: {test_password}")
    print("-" * 60)

    # Hash password
    hashed = manager.hash_password(test_password)
    print(f"✓ Password hashed:")
    print(f"  {hashed[:80]}..." if len(hashed) > 80 else f"  {hashed}")

    # Verify correct password
    is_valid = manager.verify_password(hashed, test_password)
    print(f"\n✓ Verify correct password: {'✅ PASS' if is_valid else '❌ FAIL'}")

    # Verify incorrect password
    is_valid = manager.verify_password(hashed, "WrongPassword")
    print(f"✓ Verify incorrect password: {'✅ PASS' if not is_valid else '❌ FAIL'}")

    # Extract hash info
    info = manager.get_hash_info(hashed)
    print(f"\n✓ Hash parameters:")
    print(f"  Algorithm: {info.get('algorithm')}")
    print(f"  Version: {info.get('version')}")
    print(f"  Memory cost: {info.get('memory_cost')} KiB ({info.get('memory_cost', 0) // 1024} MB)")
    print(f"  Time cost: {info.get('time_cost')}")
    print(f"  Parallelism: {info.get('parallelism')}")

    # Test rehash check
    needs_rehash = manager.needs_rehash(hashed)
    print(f"\n✓ Needs rehash: {'Yes' if needs_rehash else 'No'}")

    # Test with higher security parameters (simulates upgrade)
    print("\n" + "-" * 60)
    print("Testing with upgraded security parameters:")
    manager_high = Argon2Manager(time_cost=4, memory_cost=131072)  # Double memory
    needs_rehash = manager_high.needs_rehash(hashed)
    print(f"✓ Needs rehash with new params: {'Yes' if needs_rehash else 'No'}")

    print("\n" + "=" * 60)
    print("All tests completed successfully!")
    print("=" * 60)
